spring.application.name=practice

spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=purusoth45
spring.jpa.showsql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


books.empty=No books in the library
books.not.found=Books Not Found
books.list.invalid=add atleast one book before submit
book.not.found=Book Not Found
